<?= $this->extend('layouts/index_layout.php'); ?>
<?= $this->section('content'); ?>
<style>.need-to-discuss{background:#324349;position:relative}.need-to-discuss.bg-img{background:url(../public/home/images/bg/aboutus_bg.jpg) no-repeat center top / cover}.need-to-discuss.bg-img:after{width:100%;height:100%;display:block;background:#699882;background:-moz-linear-gradient(45deg,#699882 0,#708f99 100%);background:-webkit-linear-gradient(45deg,#699882 0,#708f99 100%);background:linear-gradient(45deg,#699882 0,#708f99 100%);filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#699882',endColorstr='#708f99',GradientType=1);content:"";position:absolute;left:0;top:0;opacity:.8;z-index:1}.need-to-discuss.bg-img .container{position:relative;z-index:2}.need-to-discuss .head-block{text-align:center;padding-bottom:60px}.need-to-discuss h2{padding:25px 0 20px;color:#fff}.need-to-discuss P{color:#fff;opacity:.8}.need-to-discuss .submit-form{padding-bottom:16px}.need-to-discuss .submit-form input{width:100%;background:0;border:0;border-bottom:1px #516167 solid;color:#9fb4bc;font-size:12px;padding:0 0 9px 0;margin:0 0 55px;text-transform:uppercase}.need-to-discuss .submit-form input{border-color:rgba(255,255,255,0.4)}.need-to-discuss .submit-form ::-webkit-input-placeholder{color:#fff;opacity:.5}.need-to-discuss .submit-form ::-moz-placeholder{color:#fff;opacity:.5}.need-to-discuss .submit-form :-ms-input-placeholder{color:#fff;opacity:.5}.need-to-discuss .submit-form :-moz-placeholder{color:#fff;opacity:.5}.need-to-discuss .submit-form input:focus{color:#fff;border-color:currentcolor currentcolor #fff}.need-to-discuss .submit-form .submit-btn{width:175px;margin:0 auto;background:#f29a32;border:0;border-radius:3px;color:#fff;cursor:pointer;font-size:14px;line-height:48px;text-align:center;font-weight:700;padding:0 15px;display:block;text-transform:uppercase;transition:all .3s ease 0s}.need-to-discuss .submit-form .submit-btn:hover{background:#57bce2}</style>
<section class="need-to-discuss bg-img padding-lg">
<div class="container">
<div class="row justify-content-center">
<div class="col-md-12 head-block">
<h2>About Us</h2>
<p>UniTol, short for Unique and Total Training Solutions, has been created with the vision to become the most preferred global end-to-end training solutions partner.</p>
<p class="hidden-md-down">UniTol is the go-to company for corporate entities and individuals looking for training process management and/or facilitation services. The company has leveraged on the vast experience of its core team in the area of organizational training, business consulting and travel industry.</p>
<p class="hidden-md-down">The founding team members have, over years of multi-disciplinary experience as training providers and in management of the training function and process, identified the need for a complete solution that ties together all the elements that comprise of and complete a training process. This finding, along with a long standing desire to come up with unique solutions and create true intellectual capital, propelled the team to create UniTol. The entire gamut of the solutions come together in the portal SimplifyMyTraining.com </p>
<p class="hidden-md-down">This idea could be taken from concept to reality thanks to a strong core team and valuable strategic investment partnership. The result, arrived at after detailed analysis and design, is a dedicated Training Solutions entity, providing online and offline service elements.</p>
<p>Click here to visit <a href="http://unitol.in/"><b>UniTol Training Solutions web site.</b></a> </p>
</div>
</div>
</div>
</section>

<?= $this->endsection(); ?>