<?php
$sidemenu['/admin/create_menus']="admin/menucreation";
$sidemenu['/admin/menucreation']="admin/menucreation";
$sidemenu['/admin/viewmenu']="admin/menucreation";
$sidemenu['/admin/role']="admin/role";
$sidemenu['/admin/create_role']="admin/role";
$sidemenu['/admin/role_view']="admin/role";
$sidemenu['/admin/user_creation']="admin/user_creation";
$sidemenu['/admin/user_view']="admin/user_creation";
$sidemenu['/admin/create_user']="admin/user_creation";
$sidemenu['/admin/master_home']="admin/master_home";
$sidemenu['/admin/view_masters']="admin/master_home";
$sidemenu['/admin/masters']="admin/master_home";
$sidemenu['/admin/notificationsearch']="admin/notificationsearch";
$sidemenu['/admin/notification']="admin/notificationsearch";
$sidemenu['/admin/notificatio_view']="admin/notificationsearch";
$sidemenu['/admin/location_search']="admin/location_search";
$sidemenu['/admin/location']="admin/location_search";
$sidemenu['/admin/location_creation']="admin/location_search";
$sidemenu['/admin/location_view']="admin/location_search";
$sidemenu['/admin/organization']="admin/organization";
$sidemenu['/admin/org_master']="admin/organization";
$sidemenu['/admin/org_master_view']="admin/organization";
$sidemenu['/admin/hierarchy_master']="admin/hierarchy_master";
$sidemenu['/admin/org_hierarchy']="admin/hierarchy_master";
$sidemenu['/admin/org_hierarchy_view']="admin/hierarchy_master";
$sidemenu['/admin/vendor_search']="admin/vendor_search";
$sidemenu['/admin/vendor_creation']="admin/vendor_search";
$sidemenu['/admin/sales_force_search']="admin/sales_force_search";
$sidemenu['/admin/sales_employee_creation']="admin/sales_force_search";
$sidemenu['/admin/view_sales_details']="admin/sales_force_search";
$sidemenu['/admin/grade_search']="admin/grade_search";
$sidemenu['/admin/grades']="admin/grade_search";
$sidemenu['/admin/grade_view']="admin/grade_search";
$sidemenu['/admin/grade_update']="admin/grade_search";
$sidemenu['/admin/position_search']="admin/position_search";
$sidemenu['/admin/position']="admin/position_search";
$sidemenu['/admin/position_view']="admin/position_search";
$sidemenu['/admin/position_update']="admin/position_search";
$sidemenu['/admin/employee_search']="admin/employee_search";
$sidemenu['/admin/employee_creation']="admin/employee_search";
$sidemenu['/admin/view_emp_details']="admin/employee_search";
$sidemenu['/admin/budget_search']="admin/budget_search";
$sidemenu['/admin/budget']="admin/budget_search";
$sidemenu['/admin/budgetupdate']="admin/budget_search";
$sidemenu['/admin/budgetview']="admin/budget_search";
$sidemenu['/admin/period_details']="admin/period_details";
$sidemenu['/admin/budget_setup']="admin/period_details";
$sidemenu['/admin/budget_view']="admin/period_details";
$sidemenu['/admin/resoures_search']="admin/resoures_search";
$sidemenu['/admin/resoures']="admin/resoures_search";
$sidemenu['/admin/resoures_view']="admin/resoures_search";
$sidemenu['/admin/group_search']="admin/group_search";
$sidemenu['/admin/group_creation']="admin/group_search";
$sidemenu['/admin/group_view']="admin/group_search";
$sidemenu['/admin/group_edit']="admin/group_search";
$sidemenu['/admin/announcements']="admin/announcements";
$sidemenu['/admin/viewannouncements']="admin/announcements";
$sidemenu['/admin/createannouncements']="admin/announcements";
$sidemenu['/admin/bulletin_search']="admin/bulletin_search";
$sidemenu['/admin/createbulletin']="admin/bulletin_search";
$sidemenu['/admin/bulletindashboard']="admin/bulletin_search";
$sidemenu['/admin/calender_search']="admin/calender_search";
$sidemenu['/admin/calender']="admin/calender_search";
$sidemenu['/admin/calender_view']="admin/calender_search";
$sidemenu['/admin/calendar_program_view']="admin/calender_search";
$sidemenu['/admin/questionbank_search']="admin/questionbank_search";
$sidemenu['/admin/questionbank_creation']="admin/questionbank_search";
$sidemenu['/admin/questionbank_view']="admin/questionbank_search";
$sidemenu['/admin/questions']="admin/questionbank_search";
$sidemenu['/admin/question_creation']="admin/questionbank_search";
$sidemenu['/admin/question_view']="admin/questionbank_search";
$sidemenu['/admin/question_update']="admin/questionbank_search";
$sidemenu['/admin/language_search']="admin/language_search";
$sidemenu['/admin/language_view']="admin/language_search";
$sidemenu['/admin/language_update']="admin/language_search";
$sidemenu['/admin/test_home']="admin/test_home";
$sidemenu['/admin/test_creation']="admin/test_home";
$sidemenu['/admin/test_view']="admin/test_home";
$sidemenu['/admin/test_edit']="admin/test_home";
$sidemenu['/admin/update_test']="admin/test_home";
$sidemenu['/admin/tna_search']="admin/tna_search";
$sidemenu['/admin/tna']="admin/tna_search";
$sidemenu['/admin/tna_details']="admin/tna_search";
$sidemenu['/admin/tna_admin_add_programs']="admin/tna_search";
$sidemenu['/admin/tna_mandatory_program']="admin/tna_search";
$sidemenu['/admin/tna_scorting_program']="admin/tna_search";
$sidemenu['/admin/tna_admin_add_emp_programs']="admin/tna_search";
$sidemenu['/admin/tna_publish']="admin/tna_search";
$sidemenu['/admin/tna_view']="admin/tna_search";
$sidemenu['/admin/tna_data_migration']="admin/tna_search";
$sidemenu['/admin/tna_details_search']="admin/tna_details_search";
$sidemenu['/admin/category']="admin/category";
$sidemenu['/admin/create_category']="admin/category";
$sidemenu['/admin/program_creation_search']="admin/program_creation_search";
$sidemenu['/admin/program_creation']="admin/program_creation_search";
$sidemenu['/admin/view_program']="admin/program_creation_search";
//$sidemenu['/admin/program_event_details']="admin/program_creation_search";
$sidemenu['/admin/event_creation']="admin/program_creation_search";
$sidemenu['/admin/event_session_search']="admin/program_creation_search";
$sidemenu['/admin/event_session_creation']="admin/program_creation_search";
$sidemenu['/admin/Notify_events']="admin/program_creation_search";
$sidemenu['/admin/project_search']="admin/program_creation_search";
$sidemenu['/admin/project_creation']="admin/program_creation_search";
$sidemenu['/admin/project_update']="admin/program_creation_search";
$sidemenu['/admin/project_add_employee']="admin/program_creation_search";
$sidemenu['/admin/eventFeedback']="admin/program_creation_search";
$sidemenu['/admin/competency_search']="admin/competency_search";
$sidemenu['/admin/competency']="admin/competency_search";
$sidemenu['/admin/competency_view']="admin/competency_search";
$sidemenu['/admin/competency_view']="admin/competency_search";
$sidemenu['/admin/ebook_search']="admin/ebook_search";
$sidemenu['/admin/ebook']="admin/ebook_search";
$sidemenu['/admin/ebook_view']="admin/ebook_search";
$sidemenu['/admin/scomaterial_search']="admin/scomaterial_search";
$sidemenu['/admin/scomaterial']="admin/scomaterial_search";
$sidemenu['/admin/nonscomaterial_search']="admin/nonscomaterial_search";
$sidemenu['/admin/ass_programs_search']="admin/ass_programs_search";
$sidemenu['/admin/ass_program_creation']="admin/ass_programs_search";
$sidemenu['/admin/nonscomaterial']="admin/nonscomaterial_search";
$sidemenu['/admin/wfpnamesearch']="admin/wfpnamesearch";
$sidemenu['/admin/wfprocess_name']="admin/wfpnamesearch";
$sidemenu['/admin/wf_process_name_view']="admin/wfpnamesearch";
$sidemenu['/admin/wfrdefsearch']="admin/wfrdefsearch";
$sidemenu['/admin/wfrole_definition']="admin/wfrdefsearch";
$sidemenu['/admin/wf_role_view']="admin/wfrdefsearch";
$sidemenu['/admin/wfrvalsearch']="admin/wfrvalsearch";
$sidemenu['/admin/wfrvalues']="admin/wfrvalsearch";
$sidemenu['/admin/wfrvalue_view']="admin/wfrvalsearch";
$sidemenu['/admin/wfrvalue_edit']="admin/wfrvalsearch";
$sidemenu['/admin/wfagroupsearch']="admin/wfagroupsearch";
$sidemenu['/admin/wfapproval_group']="admin/wfagroupsearch";
$sidemenu['/admin/wfapprovalgroup_view']="admin/wfagroupsearch";
$sidemenu['/admin/wfalevelsearch']="admin/wfalevelsearch";
$sidemenu['/admin/wfalevels']="admin/wfalevelsearch";
$sidemenu['/admin/wflevels_view']="admin/wfalevelsearch";
$sidemenu['/admin/mylearn_new']="admin/mylearn_new";
$sidemenu['/admin/lms_mylearner_details']="admin/mylearn_new";
//$sidemenu['report/reportgeneration']="report/reportgeneration";
$sidemenu['/admin/learnerpath_search']="admin/learnerpath_search";
$sidemenu['/admin/learningpath_creation']="admin/learnerpath_search";
$sidemenu['/admin/calender_preparation_search']="admin/calender_preparation_search";
$sidemenu['/admin/calender_preparation']="admin/calender_preparation_search";
$sidemenu['/admin/admin_annual_calendar']="admin/calender_preparation_search";
$sidemenu['/admin/emp_dashboard']="admin/emp_dashboard";
$sidemenu['report/reports']="report/reports";
$sidemenu['report/report_view']="report/reports";
$sidemenu['report/report_create']="report/reports";
$sidemenu['/admin/forum_topic_details']="admin/tra_forums";
$sidemenu['/admin/admin_newdashboard']="admin/profile";
$sidemenu['/admin/admin_calendardashboard']="admin/profile";
$sidemenu['/admin/learning_dashboard']="admin/profile";
$sidemenu['/admin/resource_utilization']="admin/profile";
$sidemenu['/admin/assessment_dashboard']="admin/profile";
$sidemenu['/admin/expense_dashboard']="admin/profile";
$sidemenu['/admin/tna_dashboard']="admin/profile";
$sidemenu['/admin/calender_search']="admin/calender_search";
$sidemenu['/admin/calender_fullview']="admin/calender_search";
$sidemenu['/admin/calender_activation']="admin/calender_search";
$sidemenu['/admin/calenderprogramview']="admin/calender_search";
$sidemenu['/admin/calenderpublish']="admin/calender_search";
$sidemenu['/admin/wfrule_list']="admin/wfruleslist";
$sidemenu['/admin/wf_rule_detail_view']="admin/wfruleslist";
$sidemenu['/admin/security_profile']="admin/security_search";
$sidemenu['/admin/certification']="admin/certification";
$sidemenu['/admin/event_restriction']="admin/event_restrictionsearch";
$sidemenu['/admin/admin_entry']="admin/admin_entry";
$sidemenu['/admin/survey_search']="admin/survey_search";
$sidemenu['/admin/createsurvey']="admin/survey_search";
$sidemenu['/admin/category_master_search']="admin/category_master_search";
$sidemenu['/admin/category_view']="admin/category_master_search";
$sidemenu['/admin/category_master']="admin/category_master_search";
$sidemenu['/admin/level_master_search']="admin/level_master_search";
$sidemenu['/admin/level_view']="admin/level_master_search";
$sidemenu['/admin/level_master']="admin/level_master_search";
$sidemenu['/admin/language_search']="admin/language_search";
$sidemenu['/admin/questionbank_search']="admin/questionbank_search";
$sidemenu['/admin/competency_master_search']="admin/competency_master_search";
$sidemenu['/admin/competency_master_view']="admin/competency_master_search";
$sidemenu['/admin/competency_master']="admin/competency_master_search";
$sidemenu['admin/competency_levels']="admin/competency_master_search";

$sidemenu['/admin/case_study_master_search']="admin/case_study_master_search";
$sidemenu['/admin/case_study_view']="admin/case_study_master_search";
$sidemenu['/admin/case_study_master']="admin/case_study_master_search";

$sidemenu['/admin/inbasket_exercises_master_search']="admin/inbasket_exercises_master_search";
$sidemenu['/admin/inbasket_view']="admin/inbasket_exercises_master_search";
$sidemenu['/admin/inbasket_exercises_master']="admin/inbasket_exercises_master_search";

$sidemenu['/admin/assessor_search']="admin/assessor_search";
$sidemenu['/admin/assessor_view']="admin/assessor_search";
$sidemenu['/admin/assessor_master']="admin/assessor_search";

$sidemenu['/admin/assessment_search']="admin/assessment_search";
$sidemenu['/admin/assessment_view']="admin/assessment_search";
$sidemenu['/admin/assessment_creation']="admin/assessment_search";
$sidemenu['admin/assessment_details']="admin/assessment_search";
$sidemenu['admin/assessment_question_validation']="admin/assessment_search";
$sidemenu['admin/assessment_report']="admin/assessment_search";

$sidemenu['/admin/rating_master_search']="admin/rating_master_search";
$sidemenu['/admin/rating_master']="admin/rating_master_search";
$sidemenu['/admin/rating_view']="admin/rating_master_search";

$sidemenu['/admin/zone_search']="admin/zone_search";
$sidemenu['/admin/zone_creation']="admin/zone_search";
$sidemenu['/admin/zone_view']="admin/zone_search";

$sidemenu['/admin/kra_master_search']="admin/kra_master_search";
$sidemenu['/admin/kra_view']="admin/kra_master_search";
$sidemenu['/admin/kra_master']="admin/kra_master_search";

$sidemenu['/admin/subgrade_search']="admin/subgrade_search";
$sidemenu['/admin/subgrade_view']="admin/subgrade_search";
$sidemenu['/admin/subgrade_creation']="admin/subgrade_search";

$sidemenu['/admin/emptype_search']="admin/emptype_search";
$sidemenu['/admin/emptype_view']="admin/emptype_search";
$sidemenu['/admin/emptype_creation']="admin/emptype_search";

$sidemenu['/admin/empcategory_search']="admin/empcategory_search";
$sidemenu['/admin/empcategory_view']="admin/empcategory_search";
$sidemenu['/admin/empcategory_creation']="admin/empcategory_search";

$sidemenu['/admin/indicator_search']="admin/indicator_search";
$sidemenu['/admin/indicator_view']="admin/indicator_search";
$sidemenu['/admin/indicator_update']="admin/indicator_search";

if(isset($_SESSION['user_role'])){
if($_SESSION['user_role']=="mngr"){
	$sidemenu['/admin/managerprojectsview']="admin/manager_projects";
	$sidemenu['/admin/mentorprojectsprocess']="admin/manager_projects";
	$sidemenu['/admin/learning']="admin/view_learner_corner_subordunates";
	$sidemenu['/admin/event_corner']="admin/view_learner_corner_subordunates";
	$sidemenu['/admin/eventdetails']="admin/view_learner_corner_subordunates";
	$sidemenu['/admin/mylearn_new']="admin/view_mylearning_subordunates";
	$sidemenu['/admin/lms_mylearner_details']="admin/view_mylearning_subordunates";
	$sidemenu['/admin/employee_test']="admin/view_mylearning_subordunates";
	$sidemenu['/admin/course_extention']="admin/mang_course_extention";
	$sidemenu['/admin/forum_topic_search']="admin/view_manag_forums";
	$sidemenu['/admin/forums']="admin/view_manag_forums";
	$sidemenu['/admin/forum_topics']="admin/view_manag_forums";
	$sidemenu['/admin/topic_detail']="admin/view_manag_forums";
	$sidemenu['/admin/tna_details_search_mngr']="admin/tna_details_search_mngr";
	$sidemenu['/admin/tna_mngr_step_one']="admin/tna_details_search_mngr";
	$sidemenu['/admin/tna_indididual_employee_programs']="admin/tna_details_search_mngr";
	$sidemenu['/admin/tna_employee_add_programs']="admin/tna_details_search_mngr";
	$sidemenu['/admin/tna_details_mngr_view']="admin/tna_details_search_mngr";
	$sidemenu['/admin/tna_indididual_employee_programs_view']="admin/tna_details_search_mngr";
	$sidemenu['/admin/tna_dashboard_new']="admin/tna_details_search_mngr";
	$sidemenu['/admin/manager_bulk_enroll']="admin/manager_bulk_enroll";
	$sidemenu['/admin/manager_event_corner']="admin/manager_bulk_enroll";
	$sidemenu['/admin/manager_enrollments']="admin/manager_bulk_enroll";
	$sidemenu['/admin/manager_subordinate_learner_profile']="admin/manager_subordinate_learner_profile";
	$sidemenu['/admin/learning_dashboard_new']="admin/manager_subordinate_learner_profile";
	$sidemenu['/admin/mngr_adhoc_request_home']="admin/mngr_adhoc_request_home";
	$sidemenu['/admin/mngr_adhoc_request']="admin/mngr_adhoc_request_home";
	$sidemenu['/admin/manager_projects']="admin/manager_projects";
	$sidemenu['/admin/project_dashboard_new']="admin/manager_projects";
	$sidemenu['/admin/manager_employee_competency_profile']="admin/manager_employee_competency_profile";
	$sidemenu['/admin/competency_dashboard_new']="admin/manager_employee_competency_profile";
	$sidemenu['/admin/feedback_evaluation']="admin/feedback_evaluation";
	$sidemenu['/admin/feedback_event']="admin/feedback_evaluation";
}
if($_SESSION['user_role']=="tra"){
	$sidemenu['/admin/profile_manager']="admin/tra_dashboard";
	$sidemenu['/admin/tra_myprograms']="admin/tra_myprograms";
	$sidemenu['/admin/tra_viewprg']="admin/tra_myprograms";
	$sidemenu['/admin/tra_forums']="admin/tra_forums";
	$sidemenu['/admin/forum_topic_details']="admin/tra_forums";
	$sidemenu['/admin/tra_topic_view']="admin/tra_forums";
	$sidemenu['/admin/learner_forums_comments']="admin/tra_forums";	
	$sidemenu['/admin/tra_expert']="admin/tra_expert";
}
if($_SESSION['user_role']=="emp"){
	$sidemenu['/employee/profile']="employee/profile";
	$sidemenu['/admin/profile']="admin/profile";
	$sidemenu['/employee/employee_assessment']="employee/employee_assessment";
	$sidemenu['/employee/employee_assessment_details']="employee/employee_assessment";
	$sidemenu['/admin/employee_development']="admin/employee_development";	
}
if($_SESSION['user_role']=="asr"){
	$sidemenu['assessor/profile']="assessor/profile";
	$sidemenu['assessor/assessor_assessment']="assessor/assessor_assessment";
	$sidemenu['assessor/assessor_assessment_details']="assessor/assessor_assessment";
	$sidemenu['assessor/assessor_assessment_details?']="assessor/assessor_assessment";
	$sidemenu['assessor/getassessoremployees']="assessor/assessor_assessment";	
}

}
$men="";
$uri=$_SERVER['REQUEST_URI'];
$uri=str_replace(array('/cms_coromandel/','/dms_lms/'),array('',''),$uri);
$uri=explode("?",$uri);
$uri=$uri[0];

foreach($sidemenu as $key=>$val){
	/* $kmenu=stripos($uri,$key);
	if($kmenu== false){
		$men=$val;
	} */
	
	if($key==$uri){
		$men=$val;
	} 
	
}
if(empty($men)){
	 $men=$_SERVER['REQUEST_URI'];
}
?>